### ISSUE TITLE
'Nemesis' stat for doubles

### ISSUE THREAD

**Issue by JoshNorthrup** [alexinman/elo-slack-app#15]
In doubles stats we should be able to see what single player we've lost to the most or have the worst record against, regardless of partners.

**Comment by alexinman** [comment]
Do we want to go with "lost to the most" or "the worst record against"?
If the latter, what do you mean by "the worst record against"? The worst win/loss ratio? Or just the largest difference of wins vs losses against that player?

**Comment by alexinman** [comment]
I think "lost to the most" might just become "the player I've played the most", might be better to go with "the worst record against", but then we need to define what that means.

**Comment by JoshNorthrup** [comment]
Agreed, we should go with the worst ratio, or win % to avoid dividing by 0. I also think a 'minimum matches played' threshold (3 or 4 maybe) should be used to avoid an 0-2 record being 'worse' than say 1-20.

**Comment by alexinman** [comment]
Using the largest difference of wins vs losses would also avoid the 0-2 being worse than 1-20 issue.
e.g. 
0 wins, 2 losses = 2 more losses than wins
1 win, 20 losses = 19 more losses than wins
It also avoids having to deal with dividing by zero.

But it has a similar problem to just most losses;
e.g.
1 win, 20 losses = 19 more losses than wins
50 wins, 70 losses = 20 more losses than wins
