### ISSUE TITLE
Refactor to separate text parsing logic from the Elo controller

### ISSUE THREAD

**Issue by alaindupuis-introhive** [alexinman/elo-slack-app#16]
I gave this a crack over the long weekend and it all looked like trash.

My cleanest approach so far was:
- Rename ApplicationController -> BaseController
- Make new controller ApplicationController << BaseController
- Route all traffic through ApplicationController, where the text is parsed, and then dispatch commands from there

However, something about having a "...Controller" with no actual impact on the data feels off.

Looking for some guidance.

**Comment by alexinman** [comment]
We need a CommandParser class that we can use to parse the commands provided to the EloController. It will need to be able to detect what command is being executed and then what the parameters of that command are.

**Comment by alexinman** [comment]
Done by #29
